name: artifacts & output
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
     
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: echo "Running tests..."
  
  lint:
   runs-on: ubuntu-latest
   needs: test
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '18'  
     
     - name: Install dependencies
       run: npm ci

     - name: Run linter (with debug)
       run: npm run lint -- --debug

  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci

      - name: Deploy application
        run: npm run build